on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ftp://ftp.cluster029.hosting.ovh.net
        ftp-username: jessyfc
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        server-dir: www/
